### ISSUE TITLE
Nestjs implementation

### ISSUE THREAD

**Issue by fred76** [mxstbr/passport-magic-login#10]
@tmkn @tobiaslins  @mxstbr

It is possible to implement this library into Nestjs? like others Passport strategy through @nestjs/passport or I need other way?

thanks in advance
Alberto

**Comment by EffEmPee** [comment]
Bro, did you find how to do it?

**Comment by Yetispapa** [comment]
@fred76 can you maybe provide your solution for all, who are using NestJS. This would be awesome!

**Comment by adrianbienias** [comment]
Found it useful for this case: https://www.youtube.com/watch?v=69QmlAXNgHk
