### ISSUE TITLE
Pass more data at signup

### ISSUE THREAD

**Issue by matthieuh** [mxstbr/passport-magic-login#6]
First of all, thank you this package is awesome 😍

I would have one question though: Is it possible to pass more data at signup than just the email address (like a username, language, etc.) or is it an anti-pattern with this way of authenticated a user?

**Comment by mxstbr** [comment]
I actually had the same question last night. Going to noodle about how to add this!

**Comment by mxstbr** [comment]
As of 1.0.6 you can POST any payload you want!

```JS
fetch(`/auth/magiclogin`, {
  method: `POST`,
  body: JSON.stringify({
    // `destination` is required.
    destination: email,
    // You can POST anything else in your payload...
    name: name,
  }),
  headers: { 'Content-Type': 'application/json' }
})
```

And then you can access it in `verify`! :tada:

```JS
const magicLogin = new MagicLoginStrategy({
  // "payload" contains "destination" and anything else you POST'ed
  verify: (payload, callback) => {
    console.log(payload.name)
  }
})
```

**Comment by matthieuh** [comment]
That's awesome thank you 🙏
